# Generated by Django 4.1.3 on 2022-11-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='name',
            field=models.CharField(default=1, help_text='snack name', max_length=64),
            preserve_default=False,
        ),
    ]
